<AppScreenManager>:

    Screen:
        name: "Menu 1"
        BoxLayout:
            orientation: 'vertical'
            ToggleButton:
                text:"Continue previous test run"
                size_hint: 0.5, 0.2
                pos_hint:{"center_x":0.5,"center_y":0.5}
                group: "a1"
                id: continue
                state: "down"
                on_press:
            ToggleButton:
                text:"Start a new test run"
                size_hint: 0.5, 0.2
                pos_hint:{"center_x":0.5,"center_y":0.5}
                group: "a1"
                id: new
                on_press:
            Button:
                text: "Start"
                size_hint: 0.5, 0.5
                pos_hint:{"center_x":0.5,"center_y":0.5}

                on_press: app.selection_set()

    Screen:
        name: "Screen 1"
        GridLayout:
            cols: 3

            AnchorLayout:
                anchor_x: "left"
                anchor_y: "top"
                ToggleButton:
                    text: "1"
                    size_hint: None, None
                    size: 60, 60
                    on_state: app.toggle_state_change(self)

            AnchorLayout:
                anchor_x: "center"
                anchor_y: "top"
                ToggleButton:
                    text: "2"
                    size_hint: None, None
                    size: 60, 60
                    on_state: app.toggle_state_change(self)

            AnchorLayout:
                anchor_x: "right"
                anchor_y: "top"
                ToggleButton:
                    text: "3"
                    size_hint: None, None
                    size: 60, 60
                    on_state: app.toggle_state_change(self)

            AnchorLayout:
                anchor_x: "left"
                anchor_y: "center"
                ToggleButton:
                    text: "4"
                    size_hint: None, None
                    size: 60, 60
                    on_state: app.toggle_state_change(self)
                    
            AnchorLayout:
                anchor_x: "center"
                anchor_y: "center"
                ToggleButton:
                    text: "5"
                    size_hint: None, None
                    size: 60, 60
                    on_state: app.toggle_state_change(self)

            AnchorLayout:
                anchor_x: "right"
                anchor_y: "center"
                ToggleButton:
                    text: "6"
                    size_hint: None, None
                    size: 60, 60
                    on_state: app.toggle_state_change(self)

            AnchorLayout:
                anchor_x: "left"
                anchor_y: "bottom"
                ToggleButton:
                    text: "7"
                    size_hint: None, None
                    size: 60, 60
                    on_state: app.toggle_state_change(self)
                    
            AnchorLayout:
                anchor_x: "center"
                anchor_y: "bottom"
                ToggleButton:
                    text: "8"
                    size_hint: None, None
                    size: 60, 60
                    on_state: app.toggle_state_change(self)

            AnchorLayout:
                anchor_x: "right"
                anchor_y: "bottom"
                AnchorLayout:
                    anchor_x: "left"
                    anchor_y: "bottom"
                    Button:
                        text: "OK"
                        size_hint: None, None
                        size: 60, 60
                        on_press: app.validate_touchPoint()
                AnchorLayout:
                    anchor_x: "right"
                    anchor_y: "bottom"
                    ToggleButton:
                        text: "9"
                        size_hint: None, None
                        size: 60, 60
                        on_state: app.toggle_state_change(self)
            

    Screen:
        name: "Screen 2"





#
#        BoxLayout:
#            Button:
#                text: "Next screen"
#                on_press: app.manager.pop()
#


                    # canvas.before:
                    #     Color:
                    #         rgba: 1, 0, 0, 1
                    #     Rectangle:
                    #         pos: self.pos
                    #         size: self.size      
    